#%RAML 1.0 NamedExample
{
  "apiName": "domain-exp-customer",
  "version": "1.0.0-SNAPSHOT",
  "correlationId": "97a9ef90-b4f0-11ec-9f6f-88e9fe7dffb0",
  "timestamp": "2022-04-05T15:56:37.609+01:00",
  "errorMessage": "HTTP POST on resource 'http://domain-proc-customer.us-e2.cloudhub.io/api/customer' failed: bad request (400).",
  "errorDetails": {
    "errorCode": 500,
    "errorMessage": "The server was unable to process the request due to an internal error",
    "additionalInfo": "domain-sys-customer-1.0.0-SNAPSHOT"
  }
}